[package]
name = "tl-mltl-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
sha2 = "=0.10.9"
tl-mltl = { path = ".." }
tl-syntax = { version = "=0.3.0", git = "https://github.com/agent-ix/tl-syntax.git", rev = "fed48a2fab3f5277131a7012e1a8d10993330cb1", default-features = false, features = ["alloc", "serde"] }

[[bin]]
name = "c2po_map"
path = "fuzz_targets/c2po_map.rs"
test = false
doc = false
bench = false

[[bin]]
name = "closed_eval"
path = "fuzz_targets/closed_eval.rs"
test = false
doc = false
bench = false

[workspace]
members = ["."]
